# Generated by Django 4.2.4 on 2023-09-17 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0001_initial"),
        ("history", "0003_rename_computershistory_computerhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computerhistory",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="monitorhistory",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="networkdevicehistory",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="otherequipmenthistory",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="phonehistory",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="printershistory",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.employee",
                verbose_name="Сотрудник",
            ),
        ),
    ]
