# Generated by Django 4.2.4 on 2024-01-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_rename_printershistory_printerhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphicscardhistory',
            old_name='graphics_card',
            new_name='graphicscard',
        ),
        migrations.RenameField(
            model_name='networkcardhistory',
            old_name='network_card',
            new_name='networkcard',
        ),
        migrations.RenameField(
            model_name='networkdevicehistory',
            old_name='network_device',
            new_name='networkdevice',
        ),
        migrations.RenameField(
            model_name='othercomponenthistory',
            old_name='other_component',
            new_name='othercomponent',
        ),
        migrations.RenameField(
            model_name='otherequipmenthistory',
            old_name='other_equipment',
            new_name='otherequipment',
        ),
        migrations.RenameField(
            model_name='powersupplyhistory',
            old_name='power_supply',
            new_name='powersupply',
        ),
    ]
