# Generated by Django 4.2.4 on 2024-01-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "history",
            "0006_rename_graphics_card_graphicscardhistory_graphicscard_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="computerhistory",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата возврата"
            ),
        ),
        migrations.AlterField(
            model_name="computerhistory",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выдачи"
            ),
        ),
        migrations.AlterField(
            model_name="monitorhistory",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата возврата"
            ),
        ),
        migrations.AlterField(
            model_name="monitorhistory",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выдачи"
            ),
        ),
        migrations.AlterField(
            model_name="networkdevicehistory",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата возврата"
            ),
        ),
        migrations.AlterField(
            model_name="networkdevicehistory",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выдачи"
            ),
        ),
        migrations.AlterField(
            model_name="otherequipmenthistory",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата возврата"
            ),
        ),
        migrations.AlterField(
            model_name="otherequipmenthistory",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выдачи"
            ),
        ),
        migrations.AlterField(
            model_name="phonehistory",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата возврата"
            ),
        ),
        migrations.AlterField(
            model_name="phonehistory",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выдачи"
            ),
        ),
        migrations.AlterField(
            model_name="printerhistory",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата возврата"
            ),
        ),
        migrations.AlterField(
            model_name="printerhistory",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выдачи"
            ),
        ),
    ]
