# Generated by Django 4.2.4 on 2023-08-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComponentStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Статус компонента",
                "verbose_name_plural": "Статусы компонентов",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Модель"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="Дата приобретения")),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Категория оборудования",
                "verbose_name_plural": "Категории оборудования",
            },
        ),
        migrations.CreateModel(
            name="EquipmentStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Статус оборудования",
                "verbose_name_plural": "Статусы оборудования",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("address", models.CharField(max_length=500, verbose_name="Адрес")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
            },
        ),
        migrations.CreateModel(
            name="MemoryType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип памяти",
                "verbose_name_plural": "Типы памяти",
            },
        ),
        migrations.CreateModel(
            name="StorageType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип хранения",
                "verbose_name_plural": "Типы хранения",
            },
        ),
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компьютер",
                "verbose_name_plural": "Компьютеры",
            },
            bases=("catalogs.equipment",),
        ),
        migrations.CreateModel(
            name="NetworkDevice",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сетевое устройство",
                "verbose_name_plural": "Сетевые устройства",
            },
            bases=("catalogs.equipment",),
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телефон",
                "verbose_name_plural": "Телефоны",
            },
            bases=("catalogs.equipment",),
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Принтер",
                "verbose_name_plural": "Принтеры",
            },
            bases=("catalogs.equipment",),
        ),
        migrations.CreateModel(
            name="Peripherals",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Периферийное устройство",
                "verbose_name_plural": "Периферийные устройства",
            },
        ),
        migrations.CreateModel(
            name="OtherComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала использования"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания использования",
                    ),
                ),
                (
                    "component_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.componentstatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Другой компонент",
                "verbose_name_plural": "Другие компоненты",
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.equipmentcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="equipment_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.equipmentstatus",
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.manufacturer",
                verbose_name="Производитель",
            ),
        ),
        migrations.CreateModel(
            name="ComputerMovementHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Дата выдачи")),
                (
                    "return_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата возврата"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.location",
                        verbose_name="Местоположение",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала использования"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания использования",
                    ),
                ),
                ("capacity", models.IntegerField(verbose_name="Объем")),
                (
                    "interface",
                    models.CharField(max_length=50, verbose_name="Интерфейс"),
                ),
                (
                    "component_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.componentstatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "storage_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="catalogs.storagetype",
                        verbose_name="Тип хранения",
                    ),
                ),
                (
                    "in_computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.computer",
                        verbose_name="Компьютер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала использования"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания использования",
                    ),
                ),
                ("capacity", models.IntegerField(verbose_name="Объем")),
                ("frequency", models.IntegerField(verbose_name="Частота")),
                (
                    "component_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.componentstatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "memory_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.memorytype",
                        verbose_name="Тип памяти",
                    ),
                ),
                (
                    "in_computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.computer",
                        verbose_name="Компьютер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Processor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала использования"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания использования",
                    ),
                ),
                ("num_cores", models.IntegerField(verbose_name="Количество ядер")),
                ("frequency", models.IntegerField(verbose_name="Частота")),
                (
                    "component_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.componentstatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "in_computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.computer",
                        verbose_name="Компьютер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PowerSupply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала использования"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания использования",
                    ),
                ),
                ("power", models.IntegerField(verbose_name="Мощность")),
                (
                    "component_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.componentstatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "in_computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.computer",
                        verbose_name="Компьютер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NetworkCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала использования"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания использования",
                    ),
                ),
                ("speed", models.CharField(max_length=20, verbose_name="Скорость")),
                (
                    "card_type",
                    models.CharField(max_length=50, verbose_name="Тип сетевой карты"),
                ),
                (
                    "component_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.componentstatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "in_computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.computer",
                        verbose_name="Компьютер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала использования"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания использования",
                    ),
                ),
                (
                    "socket_type",
                    models.CharField(max_length=50, verbose_name="Тип сокета"),
                ),
                (
                    "component_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.componentstatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "supported_memory_types",
                    models.ManyToManyField(
                        to="catalogs.memorytype",
                        verbose_name="Поддерживаемые типы памяти",
                    ),
                ),
                (
                    "in_computer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.computer",
                        verbose_name="Компьютер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GraphicsCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала использования"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания использования",
                    ),
                ),
                (
                    "memory",
                    models.CharField(max_length=20, verbose_name="Объем памяти"),
                ),
                ("frequency", models.IntegerField(verbose_name="Частота")),
                (
                    "component_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.componentstatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "in_computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.computer",
                        verbose_name="Компьютер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cooler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала использования"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания использования",
                    ),
                ),
                (
                    "cooler_type",
                    models.CharField(max_length=50, verbose_name="Тип кулера"),
                ),
                ("size", models.CharField(max_length=20, verbose_name="Размер")),
                (
                    "component_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.componentstatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "in_computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.computer",
                        verbose_name="Компьютер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Серийный номер"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инвентарный номер"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала использования"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания использования",
                    ),
                ),
                (
                    "case_type",
                    models.CharField(max_length=50, verbose_name="Тип корпуса"),
                ),
                ("num_bays", models.IntegerField(verbose_name="Количество отсеков")),
                (
                    "component_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.componentstatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "in_computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.computer",
                        verbose_name="Компьютер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
