# Generated by Django 4.2.4 on 2023-08-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purchase_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EquipmentStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "basecomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.basecomponent",
                    ),
                ),
                ("case_type", models.CharField(max_length=50)),
                ("num_bays", models.IntegerField()),
            ],
            bases=("catalogs.basecomponent",),
        ),
        migrations.CreateModel(
            name="Cooler",
            fields=[
                (
                    "basecomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.basecomponent",
                    ),
                ),
                ("cooler_type", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=20)),
            ],
            bases=("catalogs.basecomponent",),
        ),
        migrations.CreateModel(
            name="GraphicsCard",
            fields=[
                (
                    "basecomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.basecomponent",
                    ),
                ),
                ("memory", models.CharField(max_length=20)),
                ("core_frequency", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=("catalogs.basecomponent",),
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                (
                    "basecomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.basecomponent",
                    ),
                ),
                ("socket_type", models.CharField(max_length=50)),
                ("supported_memory_types", models.CharField(max_length=100)),
            ],
            bases=("catalogs.basecomponent",),
        ),
        migrations.CreateModel(
            name="NetworkCard",
            fields=[
                (
                    "basecomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.basecomponent",
                    ),
                ),
                ("speed", models.CharField(max_length=20)),
                ("card_type", models.CharField(max_length=50)),
            ],
            bases=("catalogs.basecomponent",),
        ),
        migrations.CreateModel(
            name="PowerSupply",
            fields=[
                (
                    "basecomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.basecomponent",
                    ),
                ),
                ("power", models.IntegerField()),
            ],
            bases=("catalogs.basecomponent",),
        ),
        migrations.CreateModel(
            name="Processor",
            fields=[
                (
                    "basecomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.basecomponent",
                    ),
                ),
                ("num_cores", models.IntegerField()),
                ("frequency", models.DecimalField(decimal_places=2, max_digits=5)),
                ("cache_size", models.CharField(max_length=50)),
            ],
            bases=("catalogs.basecomponent",),
        ),
        migrations.CreateModel(
            name="RAM",
            fields=[
                (
                    "basecomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.basecomponent",
                    ),
                ),
                ("memory_type", models.CharField(max_length=50)),
                ("capacity", models.CharField(max_length=20)),
                ("frequency", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=("catalogs.basecomponent",),
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "basecomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.basecomponent",
                    ),
                ),
                ("storage_type", models.CharField(max_length=50)),
                ("capacity", models.CharField(max_length=20)),
                ("interface", models.CharField(max_length=50)),
            ],
            bases=("catalogs.basecomponent",),
        ),
        migrations.CreateModel(
            name="EquipmentMovementHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.employee",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.equipment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.equipmentcategory",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="components",
            field=models.ManyToManyField(
                blank=True, related_name="components_relay", to="catalogs.basecomponent"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogs.manufacturer"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.equipmentstatus",
            ),
        ),
        migrations.AddField(
            model_name="basecomponent",
            name="in_equipment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_relay",
                to="catalogs.equipment",
            ),
        ),
        migrations.AddField(
            model_name="basecomponent",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogs.manufacturer"
            ),
        ),
        migrations.AddField(
            model_name="basecomponent",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.equipmentstatus",
            ),
        ),
    ]
