# Generated by Django 4.2.4 on 2023-08-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecomponent',
            name='inventory_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='serial_number',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
