# Generated by Django 4.2.4 on 2023-08-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={
                "verbose_name": "Компоненты оборудования",
                "verbose_name_plural": "Компоненты оборудования",
            },
        ),
        migrations.AlterModelOptions(
            name="cooler",
            options={
                "verbose_name": "Компоненты оборудования",
                "verbose_name_plural": "Компоненты оборудования",
            },
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.AlterModelOptions(
            name="graphicscard",
            options={
                "verbose_name": "Компоненты оборудования",
                "verbose_name_plural": "Компоненты оборудования",
            },
        ),
        migrations.AlterModelOptions(
            name="motherboard",
            options={
                "verbose_name": "Материнская плата",
                "verbose_name_plural": "Материнские платы",
            },
        ),
        migrations.AlterModelOptions(
            name="networkcard",
            options={
                "verbose_name": "Компоненты оборудования",
                "verbose_name_plural": "Компоненты оборудования",
            },
        ),
        migrations.AlterModelOptions(
            name="powersupply",
            options={
                "verbose_name": "Компоненты оборудования",
                "verbose_name_plural": "Компоненты оборудования",
            },
        ),
        migrations.AlterModelOptions(
            name="processor",
            options={
                "verbose_name": "Компоненты оборудования",
                "verbose_name_plural": "Компоненты оборудования",
            },
        ),
        migrations.AlterModelOptions(
            name="ram",
            options={
                "verbose_name": "Компоненты оборудования",
                "verbose_name_plural": "Компоненты оборудования",
            },
        ),
        migrations.AlterModelOptions(
            name="storage",
            options={
                "verbose_name": "Компоненты оборудования",
                "verbose_name_plural": "Компоненты оборудования",
            },
        ),
    ]
