# Generated by Django 4.2.4 on 2023-08-27 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0002_alter_case_options_alter_cooler_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ComputerMovementHistory",
        ),
    ]
