# Generated by Django 4.2.4 on 2023-09-02 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0003_delete_computermovementhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherEquipment",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogs.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Другое оборудование",
                "verbose_name_plural": "Другое оборудование",
            },
            bases=("catalogs.equipment",),
        ),
    ]
