# Generated by Django 4.2.4 on 2023-09-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_otherequipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='cooler',
            options={'verbose_name': 'Система охлаждения', 'verbose_name_plural': 'Системы охлаждения'},
        ),
        migrations.AlterModelOptions(
            name='graphicscard',
            options={'verbose_name': 'Видеокарта', 'verbose_name_plural': 'Видеокарты'},
        ),
        migrations.AlterModelOptions(
            name='networkcard',
            options={'verbose_name': 'Сетевая карта', 'verbose_name_plural': 'Сетевые карты'},
        ),
        migrations.AlterModelOptions(
            name='powersupply',
            options={'verbose_name': 'Блок питания', 'verbose_name_plural': 'Блоки питания'},
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={'verbose_name': 'Процессор', 'verbose_name_plural': 'Процессоры'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'Оперативная память', 'verbose_name_plural': 'Оперативная память'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Накопитель', 'verbose_name_plural': 'Накопители'},
        ),
    ]
