# Generated by Django 4.2.4 on 2023-09-05 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_alter_case_options_alter_cooler_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocketType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип сокета',
                'verbose_name_plural': 'Типы сокетов',
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='component_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.componentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='case',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='component_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.componentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='component_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.componentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='component_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.componentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='networkcard',
            name='component_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.componentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='networkcard',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='othercomponent',
            name='component_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.componentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='othercomponent',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='component_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.componentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='component_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.componentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='component_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.componentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='component_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.componentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='processor',
            name='socket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.sockettype', verbose_name='Сокет'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.sockettype', verbose_name='Сокет'),
        ),
    ]
