# Generated by Django 4.2.4 on 2023-09-10 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipments.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Монитор",
                "verbose_name_plural": "Мониторы",
            },
            bases=("equipments.equipment",),
        ),
    ]
