# Generated by Django 4.2.4 on 2024-01-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0002_monitor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="purchase_date",
            field=models.DateTimeField(verbose_name="Дата приобретения"),
        ),
    ]
