# Generated by Django 4.2.4 on 2024-01-07 06:33

import components.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0003_alter_case_start_date_alter_cooler_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="start_date",
            field=models.DateTimeField(
                default=components.models.get_datetime_now,
                verbose_name="Дата начала использования",
            ),
        ),
        migrations.AlterField(
            model_name="cooler",
            name="start_date",
            field=models.DateTimeField(
                default=components.models.get_datetime_now,
                verbose_name="Дата начала использования",
            ),
        ),
        migrations.AlterField(
            model_name="graphicscard",
            name="start_date",
            field=models.DateTimeField(
                default=components.models.get_datetime_now,
                verbose_name="Дата начала использования",
            ),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="start_date",
            field=models.DateTimeField(
                default=components.models.get_datetime_now,
                verbose_name="Дата начала использования",
            ),
        ),
        migrations.AlterField(
            model_name="networkcard",
            name="start_date",
            field=models.DateTimeField(
                default=components.models.get_datetime_now,
                verbose_name="Дата начала использования",
            ),
        ),
        migrations.AlterField(
            model_name="othercomponent",
            name="start_date",
            field=models.DateTimeField(
                default=components.models.get_datetime_now,
                verbose_name="Дата начала использования",
            ),
        ),
        migrations.AlterField(
            model_name="powersupply",
            name="start_date",
            field=models.DateTimeField(
                default=components.models.get_datetime_now,
                verbose_name="Дата начала использования",
            ),
        ),
        migrations.AlterField(
            model_name="processor",
            name="start_date",
            field=models.DateTimeField(
                default=components.models.get_datetime_now,
                verbose_name="Дата начала использования",
            ),
        ),
        migrations.AlterField(
            model_name="ram",
            name="start_date",
            field=models.DateTimeField(
                default=components.models.get_datetime_now,
                verbose_name="Дата начала использования",
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="start_date",
            field=models.DateTimeField(
                default=components.models.get_datetime_now,
                verbose_name="Дата начала использования",
            ),
        ),
    ]
